### ISSUE TITLE
Restrict log batches based on chronological order and time span

### ISSUE THREAD

**Issue by amekkawi** [amekkawi/cwlogs-writable#2]
According to the [CloudWatch Logs API](http://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_PutLogEvents.html), log events in a PutLogEvents API call...

* Must be in chronological order by their timestamps.
* Cannot span more than 24 hours.

Proposed changes:

* Change `CWLogsWritable#nextLogBatchSize` to stop adding to the batch size if...
   * A queued log event has an older `timestamp` than the previous log event in the queue.
   * A queued log event has a `timestamp` that is more than 24 hours ahead of the first log event that would be part of the batch.

**Comment by kretz** [comment]
Integrated cwlogs-writable yesterday and saw this same problem in the wild today.

> InvalidParameterException: Log events in a single PutLogEvents request must be in chronological order.

Related question - this problem threw an error crashing nodejs. Is there any way to catch that in the mean time?

**Comment by amekkawi** [comment]
Thanks @kretz. While I don't have a solution for the issue yet I'll prioritize this ticket to get support in the library.

However, the library should be catching errors and not crashing your node process. Do you have a stack trace for the error?

**Comment by amekkawi** [comment]
Resolved with [release v0.4.0](https://github.com/amekkawi/cwlogs-writable/releases/tag/v0.4.0).

**Comment by kretz** [comment]
Thanks for the quick fix. Below is the error I got before the fix.

```
InvalidParameterException: Log events in a single PutLogEvents request must be in chronological order.
at Request.extractError (/var/app/current/node_modules/aws-sdk/lib/protocol/json.js:43:27)
at Request.callListeners (/var/app/current/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
at Request.emit (/var/app/current/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
at Request.emit (/var/app/current/node_modules/aws-sdk/lib/request.js:668:14)
at Request.transition (/var/app/current/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/var/app/current/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /var/app/current/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/var/app/current/node_modules/aws-sdk/lib/request.js:38:9)
at Request.<anonymous> (/var/app/current/node_modules/aws-sdk/lib/request.js:670:12)
at Request.callListeners (/var/app/current/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
at Request.emit (/var/app/current/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
at Request.emit (/var/app/current/node_modules/aws-sdk/lib/request.js:668:14)
at Request.transition (/var/app/current/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/var/app/current/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /var/app/current/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/var/app/current/node_modules/aws-sdk/lib/request.js:38:9)
```

**Comment by amekkawi** [comment]
Thanks for the call stack! I created #15 to address the bug.

In the mean time, you could add an `error` event listener to the stream to make sure the error isn't thrown.

```javascript
var stream = new CWLogsWritable({ ... });

// Add at least one `error` handler to avoid the thrown error.
stream.on('error', function() {});
